services:
  - type: static
    name: map-qld-frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE
        value: https://qlds-mapper-queensla.onrender.com
      - key: BUILD_TARGET
        value: render
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
